{{- if .Values.gkecluster.create }}
apiVersion: container.gcp.upbound.io/v1beta1
kind: Cluster
metadata:
  name: {{ include "my-gcp-factory.name" . }}-gkecluster
  labels:
    service: cluster
    creation: crossplane
    instance: {{ .Values.instance.name }}
spec:
  forProvider:
    minMasterVersion: {{ .Values.gkecluster.version | quote }}
    location: {{ .Values.network.region }}
    networkConfig:
      enableIntraNodeVisibility: true
    loggingService: logging.googleapis.com/kubernetes
    monitoringService: monitoring.googleapis.com/kubernetes
    addonsConfig:
      gcePersistentDiskCsiDriverConfig:
        enabled: true
    networkRef:
      name: {{ include "my-gcp-factory.name" . }}-vpc
    subnetworkRef:
      name: {{ include "my-gcp-factory.name" . }}-subnet
    ipAllocationPolicy:
      useIpAliases: true
      createSubnetwork: false
      clusterSecondaryRangeName: pods
      servicesSecondaryRangeName: services
  writeConnectionSecretToRef:
    namespace: {{ .Values.instance.name }}
    name: {{ include "my-gcp-factory.name" . }}-gkeconn
  providerConfigRef:
    name: {{ .Values.provider.gcp.config }}
---
apiVersion: container.gcp.upbound.io/v1beta1
kind: NodePool
metadata:
  name: {{ include "my-gcp-factory.name" . }}-nodepool
  labels:
    service: nodepool
    creation: crossplane
    instance: {{ .Values.instance.name }}
spec:
  forProvider:
    autoscaling:
      autoprovisioned: false
      enabled: false
    clusterRef:
      name: {{ include "my-gcp-factory.name" . }}-gkecluster
    config:
      machineType: {{ .Values.gkecluster.machineType }}
      sandboxConfig:
        type: gvisor
      diskSizeGb: 120
      diskType: pd-ssd
      imageType: cos_containerd
      oauthScopes:
      - "https://www.googleapis.com/auth/devstorage.read_only"
      - "https://www.googleapis.com/auth/logging.write"
      - "https://www.googleapis.com/auth/monitoring"
      - "https://www.googleapis.com/auth/servicecontrol"
      - "https://www.googleapis.com/auth/service.management.readonly"
      - "https://www.googleapis.com/auth/trace.append"      
    initialNodeCount: 1
    nodeLocations:
      - "{{ .Values.network.region }}-b"
      - "{{ .Values.network.region }}-c"
      - "{{ .Values.network.region }}-d"
  providerConfigRef:
    name: {{ .Values.provider.gcp.config }}
{{- end -}}