apiVersion: compute.gcp.upbound.io/v1beta1
kind: NetworkPeering
metadata:
  labels:
    service: nodepool
    creation: crossplane
    instance: {{ .Values.instance.name }}
  name: {{ include "my-gcp-factory.name" . }}-peering-vms
spec:
  forProvider:
    networkRef:
      name: {{ include "my-gcp-factory.name" . }}-vpc-vms
    peerNetworkRef:
      name: {{ include "my-gcp-factory.name" . }}-vpc
  providerConfigRef:
    name: {{ .Values.provider.gcp.config }}