apiVersion: compute.gcp.upbound.io/v1beta1
kind: Subnetwork
metadata:
  name: {{ include "my-gcp-factory.name" . }}-subnet
  labels:
     service: subnetwork
     creation: crossplane
     instance: {{ .Values.instance.name }}
spec:
  forProvider:
    region: {{ .Values.network.region }}
    ipCidrRange: {{ .Values.network.primarySubnet.nodesCidrRange }}
    privateIpGoogleAccess: true
    secondaryIpRange:
      - rangeName: pods
        ipCidrRange: {{ .Values.network.secondarySubnet.podsCidrRange }}
      - rangeName: services
        ipCidrRange: {{ .Values.network.secondarySubnet.servicesCidrRange }}
    networkRef:
      name: {{ include "my-gcp-factory.name" . }}-vpc
  providerConfigRef:
     name: {{ .Values.provider.gcp.config }}