apiVersion: compute.gcp.crossplane.io/v1beta1
kind: Subnetwork
metadata:
  name: {{ include "my-gcp-factory.name" . }}-subnet
  labels:
     service: subnetwork
     creation: crossplane
     instance: {{ .Values.instance.name }}
spec:
  forProvider:
    region: {{ .Values.network.region }}
    ipCidrRange: {{ .Values.network.primarySubnet.nodesCidrRange }}
    privateIpGoogleAccess: true
    secondaryIpRanges:
      - rangeName: pods
        ipCidrRange: {{ .Values.network.secondarySubnet.podsCidrRange }}
      - rangeName: services
        ipCidrRange: {{ .Values.network.secondarySubnet.servicesCidrRange }}
    networkSelector:
      matchLabels:
        service: network
        creation: crossplane
        instance: {{ .Values.instance.name }}
  providerConfigRef:
     name: {{ .Values.provider.gcp.config }}