apiVersion: compute.gcp.upbound.io/v1beta1
kind: Network
metadata:
  name: {{ include "my-gcp-factory.name" . }}
  labels:
    service: network
    creation: crossplane
    instance: {{ .Values.instance.name }}
spec:
  forProvider:
    autoCreateSubnetworks: false
    routingMode: REGIONAL
  providerConfigRef:
     name: {{ .Values.provider.gcp.config }}
