# Default values for my-gcp-factory.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

labels: {}

provider:
  gcp:
    config: default

network:
  region: europe-west1
  primarySubnet:
    nodesCidrRange: "192.168.0.0/24"
  secondarySubnet:
    podsCidrRange: "10.128.0.0/20"
    servicesCidrRange: "172.16.0.0/16"